#
# Macro file for the initialization phase of "exampleN02.cc"
# when runing in interactive mode
#
# Sets some default verbose
#
/control/verbose 0
/run/verbose 0
/event/verbose 0

#
# Create a scene handler for a specific graphics system
# (Edit the next line(s) to choose another graphics system)
#
#/vis/open OGLIX 600x600-0+0
/vis/open HepRepFile
/vis/heprep/setFileName heprep1
###############
#
# draw scene
#
###############
/vis/drawVolume
#
#/vis/viewer/set/hiddenEdge 0
#/vis/viewer/set/viewpointThetaPhi 90 0 deg
#/vis/viewer/zoom 4
#
# for drawing the tracks
/vis/scene/add/trajectories smooth
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
# for drawing the hits, uncomment next line
/vis/scene/add/hits
# (if you prefer refreshing each event, comment out next line)
/vis/scene/endOfEventAction accumulate
#
# max number of particles recorded is 418,573 (from 9,999,990 initial)
#/run/beamOn 418570 
# for a quick/testing run (includes @ least 1 on target particle)
/run/beamOn 1 